export const equipmentLabels = {
  parent_equipment_id: 'Parent machine?',
  parent_equipment_question: 'Asocie à',
  site_id: 'Site',
  produit_id: 'Sur quel produit est installé le puce?',
  endroit_id: 'A quel endroit?',
  location_id: 'Emplacement',
  nfc_tag_id: 'Le puce',
  gas_type_id: 'Type de gaz:',
  equipment_type_id: "Type d'unité?",
  equipment_brand_id: 'Marque',
  installation_date: "Date d'instalaltion",
  location_precision: 'Precisez',
  serial_number: 'Numéro de série',
  remote_control_number: 'Numéro de télécommande',
  gas_weight: 'Poids de gaz:',
  is_plancher_chauffant: 'Plancheur chauffant:',
  is_plancher_raffraichssant: 'Plancheur chauf/raffraichissant:',
  is_radiateurs: 'Radiateurs:',
  ventilo_convecteurs: 'Ventilo-convecteur(s)',
  has_leak_detection: 'Detecteur de fuite:',
  last_leak_detection: 'Dernière détection de fuite:',
  next_leak_detection: 'Prochaine détection de fuite',
  unite_exterieur_type_id: 'Type unite exterieur',
  equipment_model: 'Modele',
  leak_detection_periodicity: 'Periodicite détection de fuite:',
  ballon_capacite: 'Capacité du ballon:',
  unite_interieur_type_id: 'Type unite interieur',
  finalites: 'Finalites:',
  applicable: 'le cas échéant',
};
